wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 50100000
env_name:
  desc: null
  value: HandoverEnv
_wandb:
  desc: null
  value:
    code_path: code/environment/trainwandbExtension.py
    python_version: 3.10.12
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725289423
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.12
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
